// IMPORTANT!! NOTE FOR DEVELOPER:
// THIS IS AN OFFLINE PORTABLE SOFTWARE, WITHOUT ANY ONLINE DEPENDENCIES LIKE REMOTE SERVICES, REMOTE AP OR AI OR REMOTE FILE OR FONTS
// NEVER MAKE CHANGES TO PARTS OF PROJECT THAT USER NEVER REQUESTED
// UI/UX SHOULD BE PERFECT, RESPONSIVE, SLEEK AND BUG-FREE
// USE FONTAWESOME ICONS LOCAL IN 'fonts' FOLDER IN PROJECT ROOT AND MAKE SURE YOU INCLUDE THEM IN FINAL PROJECT
// EVERYTHING IN PROGRAM UI SHOULD BE STYLED, SCROLLBARS, POPUPS, DIALOGS, OBJECTS, CHECKBOXES, DROPDOWNS, EVERYTHING
//